#!/usr/bin/env bash
set -e

# Set time to UTC
export TZ='Universal Time'

helptext() {
  echo "Usage: ./run <command>"
  echo ""
  echo "Available commands are:"
  echo "  test   Run go test suite"
  echo ""
}

test() {
  nosetests --verbosity=2 tests
}

debug_test() {
  # example: ./run debug_test tests/test_sdk.py:TestSDK.test_metric
  nosetests -s $1
}

[[ $@ ]] || { helptext; exit 0; }

case "$1" in
  help) helptext
  ;;
  test) test
  ;;
  debug_test) debug_test
  ;;
  *)
    helptext
    exit 1
  ;;
esac
